server:
  port: 18081


#Sql connector configuration
spring:
  datasource:
    username : rubin-selenica
    password : leesinfromjungle71
    url : jdbc:mysql://localhost:3306/company_expenses
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  #Console configuration

security:
  jwt:
    key: 9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338